CREATE TABLE LOAN (
	ID INT PRIMARY KEY,
	ADDRESS_STATE VARCHAR(255),
	APPLICATION_TYPE VARCHAR(255),
	EMP_LENGTH VARCHAR(255),
	EMP_TITLE VARCHAR(255),
	GRADE VARCHAR(255),
	HOME_OWNERSHIP VARCHAR(255),
	ISSUE_DATE DATE,
	LAST_CREDIT_PULL_DATE DATE,
	LAST_PAYMENT_DATE DATE,
	LOAN_STATUS VARCHAR(255),
	NEXT_PAYMENT_DATE DATE,
	MEMBER_ID INT, 
	PURPOSE VARCHAR(255),
	SUB_GRADE VARCHAR(255),
	TERM VARCHAR(255),
	VERIFICATION_STATUS VARCHAR(255),
	ANNUAL_INCOME FLOAT,
	DTI FLOAT,
	INSTALLMENT FLOAT,
	INT_RATE FLOAT,
	LOAN_AMOUNT INT,
	TOTAL_ACC INT,
	TOTAL_PAYMENT INT
);

SELECT*FROM LOAN;

-- Page 1 - Summary 

-- MOM = (MTD-PMTD)/PMTD : Calculate manually

-- 1) Total Loan Applications
	-- i) Total number of Loan Applications
		SELECT COUNT(TOTAL_PAYMENT) AS TOTAL_LOAN_APPLICATIONS FROM Loan;
		
	-- ii) Month-to-Date (MTD) Loan Applications
		SELECT COUNT(id) AS MTD_LOAN_APPLICATIONS 
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31';
		
	-- iii) Previous Month-to-Date (PMTD) Loan Applications
		SELECT COUNT(id) AS PMTD_LOAN_APPLICATIONS
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30';

-- 2) Total Funded Amount
	-- i) Total Funded Amount
		SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT FROM LOAN;
		
	-- ii) Month-to-Date (MTD) Funded Amount
		SELECT SUM(LOAN_AMOUNT) AS MTD_FUNDED_AMOUNT 
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31';
		
	-- iii) Previous Month-to-Date (PMTD) Funded Amount
		SELECT SUM(LOAN_AMOUNT) AS PMTD_FUNDED_AMOUNT 
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30';

-- 3) Total Amount Received
	-- i) Total Amount Received
		SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM LOAN;
		
	-- ii) Month-to-Date (MTD) Amount Received
		SELECT SUM(TOTAL_PAYMENT) AS MTD_AMOUNT_RECEIVED
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31';
		
	-- iii) Previous Month-to-Date (PMTD) Amount Received
		SELECT SUM(TOTAL_PAYMENT) AS PMTD_AMOUNT_RECEIVED
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30';

-- 4) Average Interest Rate
	-- i) Total Average Interest
		SELECT AVG(INT_RATE)*100 AS TOTAL_AVERAGE_INTEREST_RATE FROM LOAN;
		
	-- ii) Month-to-Date (MTD) Average Interest Rate
		SELECT AVG(INT_RATE)*100 AS MTD_AVERAGE_INTEREST_RATE
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31';
		
	-- iii) Previous Month-to-Date (PMTD) Average Interest Rate
		SELECT AVG(INT_RATE)*100 AS PMTD_AVERAGE_INTEREST_RATE
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30';

-- 5) Average Debt-to-Income Ratio (DTI)
	-- i) Total Average Debt-to-Income Ratio (DTI)
		SELECT AVG(DTI)*100 AS TOTAL_AVERAGE_DTI FROM LOAN;
		
	-- ii) Month-to-Date (MTD) Average Debt-to-income Ratio (DTI)
		SELECT AVG(DTI)*100 AS MTD_TOTAL_AVERAGE_DTI
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31';
		
	-- iii) Previous Month-to-Date (PMTD) Average Debt-to-income Ratio (DTI)
		SELECT AVG(DTI)*100 AS PMTD_TOTAL_AVERAGE_DTI
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30';

-- 6) Good Loan Amount
	-- i) Good Loan Application Percentage
		SELECT (COUNT(CASE WHEN LOAN_STATUS='Fully Paid' OR LOAN_STATUS='Current' THEN id END)*100)/
		COUNT(id) AS GOOD_LOAN_PERCENTAGE FROM LOAN;

	-- ii) Good Loan Application
		SELECT COUNT(ID) AS GOOD_LOAN_APPLICATIONSFROM LOAN WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current';

	-- iii) Good Loan Funded Amount
		SELECT SUM(LOAN_AMOUNT) AS GOOD_LOAN_FUNDED_AMOUNT FROM LOAN WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current';

	-- iv) Good Loan Total Received Amount
		SELECT SUM(TOTAL_PAYMENT) AS GOOD_LOAN_RECEIVED_AMOUNT FROM LOAN WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current';

-- 6) Bad Loan Amount
	-- i) Bad Loan Application Percentage
		SELECT (COUNT(CASE WHEN LOAN_STATUS='Charged Off' THEN id END)*100)/
		COUNT(id) AS BAD_LOAN_PERCENTAGE FROM LOAN;

	-- ii) Bad Loan Application
		SELECT COUNT(ID) AS BAD_LOAN_APPLICATIONS FROM LOAN WHERE LOAN_STATUS = 'Charged Off';

	-- iii) Bad Loan Funded Amount
		SELECT SUM(LOAN_AMOUNT) AS BAD_LOAN_FUNDED_AMOUNT FROM LOAN WHERE LOAN_STATUS = 'Charged Off';

		-- iv) Bad Loan Total Received Amount
		SELECT SUM(TOTAL_PAYMENT) AS BAD_LOAN_RECEIVED_AMOUNT FROM LOAN WHERE LOAN_STATUS = 'Charged Off';

-- 7) Loan Status
	-- i) Over all Loan Status
		SELECT LOAN_STATUS,
			COUNT(ID) AS TOTAL_LOAN_APPLICATIONS,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
			AVG(INT_RATE*100) AS INTEREST_RATE,
			AVG(DTI*100) AS DTI
		FROM LOAN GROUP BY LOAN_STATUS;

	-- ii) Month-to-Date (MTD) Loan Status
		SELECT LOAN_STATUS,
			SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-12-01' AND '2021-12-31'
		GROUP BY LOAN_STATUS;

	-- iii) Previous Month-to-Date (PMTD) Loan Status
		SELECT LOAN_STATUS,
			SUM(TOTAL_PAYMENT) AS PMTD_TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS PMTD_TOTAL_FUNDED_AMOUNT
		FROM LOAN WHERE ISSUE_DATE BETWEEN '2021-11-01' AND '2021-11-30'
		GROUP BY LOAN_STATUS;

-- Page 2 - Overview

-- 1) Monthly Trends by Issue Date (Line Chart)
		SELECT 
			EXTRACT(MONTH FROM ISSUE_DATE),
			TO_CHAR(ISSUE_DATE, 'Month') AS MONTH_NAME,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY TO_CHAR(ISSUE_DATE, 'Month'),EXTRACT(MONTH FROM ISSUE_DATE)
		ORDER BY EXTRACT(MONTH FROM ISSUE_DATE);

-- 2) Regional Analysis by State (Filled Map)
		SELECT 
			ADDRESS_STATE,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY ADDRESS_STATE
		ORDER BY ADDRESS_STATE;

-- 3) Loan Term Analysis (Donut Chart)
		SELECT 
			TERM,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY TERM
		ORDER BY TERM;

-- 4) Employee Length Analysis (Bar Chart)
		SELECT 
			EMP_LENGTH,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY EMP_LENGTH
		ORDER BY EMP_LENGTH;

-- 5) Loan Purpose Breakdown (Bar Chart)
		SELECT 
			PURPOSE,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY PURPOSE
		ORDER BY COUNT(ID) DESC;

-- 6) Home Ownership Analysis (Tree Map)
		SELECT 
			HOME_OWNERSHIP,
			COUNT(ID) AS TOTAL_LOAN_APPLICATION,
			SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
			SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
		FROM LOAN 
		GROUP BY HOME_OWNERSHIP
		ORDER BY COUNT(ID) DESC;